// `llmux orch init` — bootstrap a transport at the default user-data path,
// optionally wired to a DR-only remote. Wraps gitInit/gitClone/gitAddRemote
// from transport.ts and chooses between "create new" and "clone existing"
// based on what the remote actually has (option A from the init-flow design).

import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import {
  type GitResult, gitInit, gitClone, gitAddRemote, probeRemote, asyncBackupPush,
} from './transport.ts';

/** XDG-correct default — transport is generated user data, not config. */
export function defaultTransportRoot(): string {
  const xdgData = process.env['XDG_DATA_HOME'] ?? join(homedir(), '.local', 'share');
  return join(xdgData, 'llmux', 'orchestration');
}

/** Current on-disk protocol version. Mirrors crosstalk's CROSSTALK-VERSION pattern. */
export const TRANSPORT_PROTOCOL_VERSION = 1;

export interface InitOptions {
  /** Target directory. Defaults to `defaultTransportRoot()`. */
  transportRoot?: string;
  /** Optional DR-only remote URL (e.g., git@github.com-personal:steve-krisjanovs/llmux-transport.git). */
  remote?: string;
}

export interface InitResult {
  transportRoot: string;
  mode: 'init' | 'clone';
  remote?: string;
}

/**
 * Initialize a transport. Behaviour:
 *
 *   no --remote                       → gitInit local skeleton, no remote
 *   --remote <empty-remote>           → gitInit local skeleton, add remote, async push
 *   --remote <populated-remote>       → gitClone the remote into the path (DR-restore path)
 *   --remote <unreachable>            → error
 *
 * Throws if the target directory already exists and is non-empty (caller
 * decides whether to point at a different path or `rm -rf` first).
 */
export function init(opts: InitOptions = {}): InitResult {
  const transportRoot = opts.transportRoot ?? defaultTransportRoot();

  // Path-exists check (the gitInit/gitClone functions also guard, but a
  // clearer error message at the entry point is operator-friendlier).
  if (existsSync(transportRoot)) {
    const { readdirSync } = require('fs');
    if (readdirSync(transportRoot).length > 0) {
      throw new Error(
        `transport path ${transportRoot} already exists and is non-empty. ` +
        `Refusing to clobber. Move it aside (\`mv ${transportRoot} ${transportRoot}.bak\`) ` +
        `or pass --transport-root <path> to use a different location.`,
      );
    }
  }

  if (opts.remote) {
    const remoteState = probeRemote(opts.remote);
    if (remoteState === 'unreachable') {
      throw new Error(
        `remote ${opts.remote} is unreachable. Check the URL + your SSH/HTTPS git auth.`,
      );
    }
    if (remoteState === 'populated') {
      // DR-restore path.
      const r = gitClone(transportRoot, opts.remote);
      throwIfNotOk(r, 'clone');
      return { transportRoot, mode: 'clone', remote: opts.remote };
    }
    // Empty remote: init local, wire remote, push.
    const initRes = gitInit(transportRoot, {
      protocolVersion: TRANSPORT_PROTOCOL_VERSION,
      readme: defaultReadme(),
      protocol: defaultProtocol(),
    });
    throwIfNotOk(initRes, 'init');
    const remoteRes = gitAddRemote(transportRoot, opts.remote);
    throwIfNotOk(remoteRes, 'add-remote');
    asyncBackupPush(transportRoot);
    return { transportRoot, mode: 'init', remote: opts.remote };
  }

  const initRes = gitInit(transportRoot, {
    protocolVersion: TRANSPORT_PROTOCOL_VERSION,
    readme: defaultReadme(),
    protocol: defaultProtocol(),
  });
  throwIfNotOk(initRes, 'init');
  return { transportRoot, mode: 'init' };
}

function throwIfNotOk(r: GitResult, stage: string): void {
  if (!r.ok) throw new Error(`${stage} failed: ${r.error ?? '<no error>'}`);
}

function defaultReadme(): string {
  return `# llmux orchestration transport

This is an llmux orchestration transport — a git repo of conversations
between agents running under a single user's \`llmuxd\`. **NOT a shared
artefact**; do not commit anything here by hand outside of the
\`data/actors/*.md\` files (which are the operator-owned actor definitions).

## Layout

\`\`\`
data/
  actors/<alias>.md             — actor definitions (operator-edited)
  channels/<channel>/YYYY/MM/DD/HHMMSSmmmZ-XXXXXXXX.md
                                — messages (dispatcher-written, append-only)
LLMUX-TRANSPORT-VERSION         — single integer; bump on incompatible schema change
PROTOCOL.md                     — on-the-wire contract (see file)
\`\`\`

## Origin remote

If a remote is configured, llmuxd async-pushes \`main\` to \`origin/main\` after
each commit. **One-way mirror for disaster recovery**, not a sync target —
there is no pull. Restore = \`git clone <url> $XDG_DATA_HOME/llmux/orchestration\`.

Generated by \`llmux orch init\`. See https://github.com/cordfuse/llmux for the framework.
`;
}

function defaultProtocol(): string {
  return `# llmux orchestration transport — protocol

Wire-compatible with cordfuse/crosstalk v7 transport format (intentional —
preserves the option of pointing a crosstalk dispatcher at this repo or
vice versa).

## Message file

Path: \`data/channels/<channel>/YYYY/MM/DD/HHMMSSmmmZ-XXXXXXXX.md\`
(\`XXXXXXXX\` = 4-byte random hex; the (\`HHMMSSmmm\`,\`hex\`) pair is collision-free
in practice).

Required frontmatter:
- \`from: <alias>\` — sender alias
- \`to: <alias>\` or \`to: [<alias>, ...]\` or \`to: all\` — recipient(s); \`all\` is broadcast
- \`timestamp: <ISO-8601>\` — sender's wall clock at write

Optional frontmatter:
- \`re: <msg-id>\` or \`re: [<msg-id>, ...]\` — parent message(s) being replied to
- \`as: <persona>\` — sender's role / persona descriptor
- \`type: workflow\` — only valid value for \`type:\` in v7+ (rejected otherwise)

Body: free-form markdown, no length limit on the wire (operator discretion).

## Activation rule

A message wakes its addressee if it has no \`re:\` (new task) OR its \`re:\`
points at a message the addressee sent. Self-sent messages are skipped.
See \`packages/llmux/src/orch/activation.ts\` for the canonical implementation.

## Cursor + claim

\`cursor\` (machine-local; not in the transport) is the last git commit hash
the dispatcher scanned. Messages are detected via \`git diff cursor..HEAD --
data/channels/\`. Claims live machine-locally too (\`claims/\<msg-id\>\`) — a
five-minute TTL with heartbeat refresh arbitrates concurrent watchers on
the same alias.

## Actor file

Path: \`data/actors/<alias>.md\`. Frontmatter: \`alias\`, \`name\`, \`description\`,
\`includes\`. Body: persona (system-prompt content). \`includes\` resolves
against local-file refs in v1.0; \`skills.sh/<slug>\` lands in v1.1.

## Ephemeral-alias semantics (#1845)

First-boot cursor seeds to HEAD. Pre-boot messages to a never-booted alias
are not delivered. An alias only exists from its first dispatcher boot
onward; there is no per-host \`join\` marker by design.
`;
}
